config/routes.rb
Rails.application.routes.draw do

  get 'admin/admin_home'

  resources :service_requests
  resources :user_service_categories
  resources :service_categories
  devise_for :users, controllers: {registrations: 'registrations'}

  get 'users/non_tasker_signup'
  
  root "pages#home"

  get 'signup' => 'pages#signup'

  get 'login' => 'pages#login'

  get 'professionals' => 'pages#tasker_home', as: 'tasker_home'

  get 'how_it_works' => 'pages#how_it_works'

  get 'privacy_policy' => 'pages#privacy_policy'

  get 'terms_of_service' => 'pages#terms_of_service'

  get 'how_can_we_help' => 'service_categories#formatted_index', as: 'service_category_formatted_index'

  get 'our_team' => 'pages#our_team'

  get 'about' => 'pages#about'

  get 'live' => 'users#live'

  get 'requests' => 'users#requests'

  get 'messages' => 'users#messages'

  get 'update_availability' => 'users#update_availability'

  get 'balance' => 'users#balance'

  get 'admin/home' => 'admin#admin_home', as: 'admin_home'
  
  get 'admin/users' => 'admin#admin_users', as: 'admin_users'

  get 'admin/service_requests' => 'admin#admin_service_requests', as: 'admin_service_requests'

  get 'admin/user/edit/:id' => 'admin#edit_user', as: 'admin_edit_user'

  get 'admin/charges' => 'admin#admin_charges', as: 'admin_charges'

  get 'signup/user' => 'users#non_tasker_signup', as: 'non_tasker_signup'

  get 'signup/tasker' => 'users#tasker_signup', as: 'tasker_signup'

  get 'account_settings' => 'users#account_settings', as: 'account_settings'

  get 'add_profile_photo' => 'users#tasker_needs_image', as: 'add_profile_photo'

  get '/service_request/check_for_acceptance/:requestID', :to => 'service_requests#check_for_acceptance'

  get 's/service_requests/initiate/' => 'service_requests#request_details', as: 'initiate_service_request_no_category'

  get 's/service_request/:service_request_id/review_details' => 'service_requests#review_details', as: 'review_service_request_details'

  get '/service_request/:id/' => 'service_requests#show', as: 'show_service_request'

  post 'service_request/:service_request_id/add_professional/:tasker_id' => 'service_requests#add_tasker', as: 'add_tasker_to_service_request'

  post 'service_request/:service_request_id/confirm_payment' => 'service_requests#confirm_payment', as: 'confirm_payment_for_service_request'

  get 'service_request/:service_request_id/confirmation' => 'service_requests#confirmation', as: 'service_request_submission_confirmation'
  

  get 'service_request/:service_request_id/pay_and_confirm' => 'service_requests#pay_and_confirm', as: 'pay_and_confirm'

  get 's/service_requests/initiate/:service_category_url' => 'service_requests#request_details', as: 'initiate_service_request'

  get 's/service_requests/initiate/:service_category_url/live' => 'service_requests#live_request_details', as: 'initiate_live_service_request'

  get 's/service_requests/initiate/:service_category_url/scheduled' => 'service_requests#scheduled_request_details', as: 'initiate_scheduled_service_request'

  get 's/service_request/:service_request_id/mark_as_complete/complete' => 'service_requests#mark_as_complete', as: 'mark_as_complete'

  get 's/service_request/:service_request_id/mark_as_cancelled/cancel' => 'service_requests#mark_as_cancelled', as: 'mark_as_cancelled'

  get 's/service_request/:service_request_id/complete/confirmation' => 'service_requests#service_request_confirm_complete', as: 'service_request_confirm_complete'

  get 's/service_request/:service_request_id/complete/cancelled' => 'service_requests#service_request_confirm_cancelled', as: 'service_request_confirm_cancelled'

  get 's/service_request/:service_request_id/admin/complete/process_payment' => 'service_requests#admin_process_payment', as: 'service_request_process_payment'

  get 'service_requests/choose_professional/:id' => 'service_requests#service_request_tasker_index', as: 'service_request_tasker_index'

  get 'service_requests/live/search/:id' => 'service_requests#live_search', as: 'service_request_live_search'

  get '/services/:category_url' => 'service_categories#tasker_index', as: 'service_category_home'

  get '/user/add_services' => 'user_service_categories#new', as: 'add_service_to_user'

  get '/user/add_services/:category_url' => 'user_service_categories#new', as: 'add_service_to_user_with_category'

  get '/user/profile/:id' => 'users#profile', as: 'user_profile'

  post 'user/profile/bank_account/add' => 'users#add_bank_account', as: 'add_bank_account'

end

app/views/admin/admin_charges.html.erb
<div class="content">

	<header><%= link_to "Admin Home", admin_home_path %> > Charges</header>

	<span class="mobile-only soft-warning">Notice: This admin page looks best on a larger screen!</span>
	
	<table class="formatted-table">

		<thead>
			
			<tr>

				<th>Date/Time</th>

				<th>Amount</th>

				<th>Service Fee</th>

				<th>Customer Email</th>

				<th>Tasker Email</th>

			</tr>

		</thead>

		<tbody>
			
			<% Charge.all.sort_by(&:created_at).reverse	.each do |charge| %>

				<tr>

					<td><%= charge.created_at.strftime("%m/%e/%y %H:%M") %></td>

					<td><%= number_to_currency(charge.amount/100) %></td>

					<td><%= number_to_currency(charge.service_fee/100) %></td>

					<td><%= User.find(charge.user_id).email %></td>

					<td><%= User.find(charge.tasker_id).email %></td>

				</tr>

			<%end%>

		</tbody>


	</table>


</div>

app/views/admin/admin_home.html.erb
<div class="content">

	<header>Admin Home</header>

	<span class="mobile-only soft-warning">Notice: This admin page looks best on a larger screen!</span>

	<div class="content">

		<div class="row"%>

			<div class="col-xs-12 col-sm-4">

				<%= link_to admin_users_path do %>
					
					<div class="card index">
						
						<div class="card-content">
							
							<p>Users<span class="glyphicon glyphicon-chevron-right" aria-hidden="true" style="float: right"></span></p>

						</div>

					</div>

				<%end%>

			</div>

			<div class="col-xs-12 col-sm-4">

				<%= link_to admin_service_requests_path do %>
					
					<div class="card index">
						
						<div class="card-content">
							
							<p>Service Requests<span class="glyphicon glyphicon-chevron-right" aria-hidden="true" style="float: right"></span></p>

						</div>

					</div>

				<%end%>

			</div>

			<div class="col-xs-12 col-sm-4">

				<%= link_to admin_charges_path do %>
					
					<div class="card index">
						
						<div class="card-content">
							
							<p>Credit Card Charges<span class="glyphicon glyphicon-chevron-right" aria-hidden="true" style="float: right"></span></p>

						</div>

					</div>

				<%end%>

			</div>
		
		</div>

	</div>

</div>

app/views/admin/admin_service_requests.html.erb
<div class="content">

	<header><%= link_to "Admin Home", admin_home_path %> > Service Requests</header>

	<span class="mobile-only soft-warning">Notice: This admin page looks best on a larger screen!</span>
	
	<table class="formatted-table">

		<thead>
			
			<tr>

				<th>Description</th>

				<th>Type</th>

				<th>Time Initiated</th>

				<th>Time Completed</th>

				<th>Time Elapsed</th>

				<th>Hours Reported</th>

				<th>Hourly Rate</th>

				<th>Total Price</th>

				<th></th>

			</tr>

		</thead>

		<tbody>
			
			<% ServiceRequest.all.sort_by(&:created_at).reverse.each do |request| %>

				<tr>

					<td><%= request.description %></td>

					<td><% if request.is_live%> Real-time <% else %> Scheduled <%end%></td>

					<td>
						<%= request.created_at.strftime("%m/%e/%y")%><br>
						<%= request.created_at.strftime("%H:%M")%>
					</td>


					<td>
						<% if request.tasker_completion_time %>
							<%= request.tasker_completion_time.strftime("%m/%e/%y") %>
							<br>
							<%= request.tasker_completion_time.strftime("%H:%M") %>
						<% end %>
					</td>

					<td>
						<%= request.time_between_request_and_completion %>
					</td>

					<td>
						<% if request.hours_reported_by_tasker%>
							<%= request.hours_reported_by_tasker %> hours 
						<%end%>
					</td>

					<td>
						<% if request.tasker_hourly_rate %><%= number_to_currency(request.tasker_hourly_rate, precision: 0) %>  / hr<%end%>
					</td>

					<td>
							
						<% if request.calculated_price %>
							<%= number_to_currency(request.calculated_price) %>
						<%end%>

					</td>

				
					<td>
						<% if request.has_pending_charge && request.calculated_price %>
							
							<%= link_to "Charge " + number_to_currency(request.calculated_price, precision: 0).to_s, service_request_process_payment_path(request.id), class:"button green-background" %>
						
						<%else%>

							<% if request.charge_approved %>

								Charge Complete
								
							<%end%>


						<%end%>
					</td>


				</tr>

			<%end%>

		</tbody>

	</table>

</div>

app/views/admin/admin_users.html.erb
<div class="content">

	<header><%= link_to "Admin Home", admin_home_path %> > Users</header>

	<span class="mobile-only soft-warning">Notice: This admin page looks best on a larger screen!</span>
	
	<table class="formatted-table">

		<thead>
			
			<tr>

				<th>ID</th>

				<th colspan="2">Name</th>

				<th>Email</th>

				<th>User Type</th>

				<th>Payment Info?</th>

				<th>Stripe Connect?</th>

				<th></th>

			</tr>

		</thead>

		<tbody>
			
			<% User.all.sort_by(&:created_at).reverse.each do |user| %>

				<tr>

					<td><%= user.id %></td>

					<td><%= image_tag user.image.url(:small), class:"small-image rounded" %></td>
					
					<td><%= user.first_name %> <%= user.last_name %></td>

					<td><%= user.email %></td>

					<td><% if user.is_tasker %>Mobile Professional<%else%>Customer<%end%></td>

					<td>
						<%if user.stripe_customer_object %>
							
							Yes

						<%else%>

							No

						<%end%>
					</td>

					<td>
						<%#if user.stripe_account_object %>
							
							

						<%#else%>

							

						<%#end%>
					</td>

				</tr>

			<%end%>

		</tbody>


	</table>

</div>

app/views/admin/edit_user.html.erb
<div class="content">

	<header class="full-screen-only">Account Settings</header>

	<div class="content medium">

		<div class="filter-option-container">

			<span class="filter-option click-to-reveal clickable active" data-reveal-panel-id="profile">Profile</span><span class="filter-option click-to-reveal clickable" data-reveal-panel-id="login">Login</span><span class="filter-option click-to-reveal clickable" data-reveal-panel-id="payments">Payments</span>

		</div>

		<div class="options-content card clear-on-mobile-device">

			<%= form_for(@user, url: registration_path(@user), html: { method: :put, class:"" }) do |f| %>

				<div class="reveal-panel" id="profile">

					<header>Profile</header>

					<div class="option-content-box">

						<div class="field">
							<label>Admin?</label><br>
							<%= f.check_box :is_admin, :value => @user.is_admin, :id => "is_admin" %>
						</div>

						<div class="field">

					      <label>Profile Photo</label><br>

					      <div class="image-field-container">
					        
					        <%= image_tag @user.image.url(:small), class:"small-image rounded" %>

					        <%= f.file_field :image, class: "small-image-overlay-input" %><br>

					      </div>

					    </div>


						<div class="field">

							<label>First Name</label><br>

						  	<%= f.text_field :first_name, placeholder: "First Name", :required => true %>
						
						</div>


						<div class="field">

							<label>Last Name</label><br>

							<%= f.text_field :last_name, placeholder: "Last Name", :required => true %>

						</div>

						<div class="field">
		  					
		  					<label>Phone Number</label><br>

						  	<%= f.text_field :phone_number, placeholder: "Phone Number", :required => true %>

						</div>


						<div class="field">
						  	
						  	<label>Address</label><br>

							<%= f.text_field :address, placeholder:"Enter Your Address", class:"geocomplete-input" %>

						</div>

					</div>

				</div>


				<div class="reveal-panel" id="login" style="display: none;">

					<header>Login</header>

					<div class="option-content-box">

						<div class="field">
		  					
		  					<label>Email</label><br>

						  	<%= f.email_field :email, placeholder: "Email", :required => true %>

						</div>

						<div class="field">
							
							<label>Password</label><br>

						  	<%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>

						</div>

					</div>

				</div>


				<div class="reveal-panel" id="payments" style="display: none;">

					<header>Payment Information</header>

					<div class="row">

						<div class="col-xs-12 col-sm-12 cc-form-row">

							<%= label_tag 'name-on-card', "Name on Card" %>
							<%= text_field_tag 'name-on-card' %>

						</div>
						<br>

						<div class="col-xs-12 col-sm-12 cc-form-row">

							<%= label_tag 'credit-card-number', "Credit Card Number" %>
							<%= text_field_tag 'credit-card-number' %>

						</div>

						<div class="col-xs-6 cc-form-row">

							<%= label_tag 'expiration-date', "Expiration Date" %>
							
							<ul class="horizontal">

								<li><select class="cc-select" name='expMonth' id='expireMM'>
							    <option value=''>Month</option>
							    <option value='01'>01</option>
							    <option value='02'>02</option>
							    <option value='03'>03</option>
							    <option value='04'>04</option>
							    <option value='05'>05</option>
							    <option value='06'>06</option>
							    <option value='07'>07</option>
							    <option value='08'>08</option>
							    <option value='09'>09</option>
							    <option value='10'>10</option>
							    <option value='11'>11</option>
							    <option value='12'>12</option>
								</select></li>
								<li><select class="cc-select" name='expYear' id='expireYY'>
							    <option value=''>Year</option>
							    <option value='16'>2016</option>
							    <option value='17'>2017</option>
							    <option value='18'>2018</option>
							    <option value='18'>2019</option>
							    <option value='18'>2020</option>
							    <option value='18'>2021</option>
							    <option value='18'>2022</option>
								</select></li>

							</ul>

						</div>

						<div class="col-xs-6 cc-form-row">

							<%= label_tag 'cvc', "CVC" %>
							<%= text_field_tag 'cvc' %>

						</div>

					</div>

				</div>

				<div class="actions centered">
							
					<br>
							
					<%= f.submit "Update", class: "button medium brand-blue-background" %>
					
				</div>

			<%end%>

		</div>

	</div>

</div>