config/routes.rb
Rails.application.routes.draw do

  get 'admin/admin_home'

  resources :service_requests
  resources :user_service_categories
  resources :service_categories
  devise_for :users, controllers: {registrations: 'registrations'}

  get 'users/non_tasker_signup'
  
  root "pages#home"

  get 'signup' => 'pages#signup'

  get 'login' => 'pages#login'

  get 'professionals' => 'pages#tasker_home', as: 'tasker_home'

  get 'how_it_works' => 'pages#how_it_works'

  get 'privacy_policy' => 'pages#privacy_policy'

  get 'terms_of_service' => 'pages#terms_of_service'

  get 'how_can_we_help' => 'service_categories#formatted_index', as: 'service_category_formatted_index'

  get 'our_team' => 'pages#our_team'

  get 'about' => 'pages#about'

  get 'live' => 'users#live'

  get 'requests' => 'users#requests'

  get 'messages' => 'users#messages'

  get 'update_availability' => 'users#update_availability'

  get 'balance' => 'users#balance'

  get 'admin/home' => 'admin#admin_home', as: 'admin_home'
  
  get 'admin/users' => 'admin#admin_users', as: 'admin_users'

  get 'admin/service_requests' => 'admin#admin_service_requests', as: 'admin_service_requests'

  get 'admin/user/edit/:id' => 'admin#edit_user', as: 'admin_edit_user'

  get 'admin/charges' => 'admin#admin_charges', as: 'admin_charges'

  get 'signup/user' => 'users#non_tasker_signup', as: 'non_tasker_signup'

  get 'signup/tasker' => 'users#tasker_signup', as: 'tasker_signup'

  get 'account_settings' => 'users#account_settings', as: 'account_settings'

  get 'add_profile_photo' => 'users#tasker_needs_image', as: 'add_profile_photo'

  get '/service_request/check_for_acceptance/:requestID', :to => 'service_requests#check_for_acceptance'

  get 's/service_requests/initiate/' => 'service_requests#request_details', as: 'initiate_service_request_no_category'

  get 's/service_request/:service_request_id/review_details' => 'service_requests#review_details', as: 'review_service_request_details'

  get '/service_request/:id/' => 'service_requests#show', as: 'show_service_request'

  post 'service_request/:service_request_id/add_professional/:tasker_id' => 'service_requests#add_tasker', as: 'add_tasker_to_service_request'

  post 'service_request/:service_request_id/confirm_payment' => 'service_requests#confirm_payment', as: 'confirm_payment_for_service_request'

  get 'service_request/:service_request_id/confirmation' => 'service_requests#confirmation', as: 'service_request_submission_confirmation'
  

  get 'service_request/:service_request_id/pay_and_confirm' => 'service_requests#pay_and_confirm', as: 'pay_and_confirm'

  get 's/service_requests/initiate/:service_category_url' => 'service_requests#request_details', as: 'initiate_service_request'

  get 's/service_requests/initiate/:service_category_url/live' => 'service_requests#live_request_details', as: 'initiate_live_service_request'

  get 's/service_requests/initiate/:service_category_url/scheduled' => 'service_requests#scheduled_request_details', as: 'initiate_scheduled_service_request'

  get 's/service_request/:service_request_id/mark_as_complete/complete' => 'service_requests#mark_as_complete', as: 'mark_as_complete'

  get 's/service_request/:service_request_id/mark_as_cancelled/cancel' => 'service_requests#mark_as_cancelled', as: 'mark_as_cancelled'

  get 's/service_request/:service_request_id/complete/confirmation' => 'service_requests#service_request_confirm_complete', as: 'service_request_confirm_complete'

  get 's/service_request/:service_request_id/complete/cancelled' => 'service_requests#service_request_confirm_cancelled', as: 'service_request_confirm_cancelled'

  get 's/service_request/:service_request_id/admin/complete/process_payment' => 'service_requests#admin_process_payment', as: 'service_request_process_payment'

  get 'service_requests/choose_professional/:id' => 'service_requests#service_request_tasker_index', as: 'service_request_tasker_index'

  get 'service_requests/live/search/:id' => 'service_requests#live_search', as: 'service_request_live_search'

  get '/services/:category_url' => 'service_categories#tasker_index', as: 'service_category_home'

  get '/user/add_services' => 'user_service_categories#new', as: 'add_service_to_user'

  get '/user/add_services/:category_url' => 'user_service_categories#new', as: 'add_service_to_user_with_category'

  get '/user/profile/:id' => 'users#profile', as: 'user_profile'

  post 'user/profile/bank_account/add' => 'users#add_bank_account', as: 'add_bank_account'

end

app/views/layouts/_footer.html.erb
<footer class="footer-container">

	<div class="footer-content">

		<div class="row">

			<div class="col-xs-12 col-sm-4">

				<section class="footer-section">

					<header class="footer-header">MY ACCOUNT</header>

					<ul>

						<% unless user_signed_in? %>
							
							<li><%= link_to "Signup", non_tasker_signup_path %></li>

							<li><%= link_to "Login", login_path %></li>

							<li><%= link_to "Become a Mobile Professional", tasker_signup_path %></li>

							<li><%= link_to "How it Works", root_path %></li>

						<%else%>

							<li><%= link_to "Account Settings", account_settings_path %></li>

							<% if current_user.is_tasker %>

								<li><%= link_to "My Profile", user_profile_path(current_user.id) %></li>
								
							<%end%>

							<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

						<%end%>

						

					</ul>

				</section>

			</div>

			<div class="col-xs-12 col-sm-4">

				<section class="footer-section">

					<header class="footer-header">COMPANY</header>

					<ul>

						<li><%= link_to "About", about_path %></li>

						<li><%= link_to "Contact Us", root_path %></li>

					</ul>

				</section>

			</div>

			<div class="col-xs-12 col-sm-4">

				<section class="footer-section">

					<header class="footer-header">SOCIAL MEDIA</header>

					<ul>

						<li><a href="https://twitter.com/_servmanity">Twitter</a></li>

						<li><a href="https://www.facebook.com/servmanity/">Facebook</a></li>

						<li><a href="https://www.instagram.com/servmanity/">Instagram</a></li>

					</ul>

				</section>


			</div>

		</div>
		
	</div>

	<br><br><br>
	<div class="centered">Copyright <%= Time.now.strftime("%Y") %> 5MT EMPOWERMENT GROUP, LLC. All Right Reserved.</div>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<head>

		<title>Servmanity</title>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

		<%= csrf_meta_tags %>

		<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
		
		<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

		<link href="https://fonts.googleapis.com/css?family=Raleway:300,400" rel="stylesheet">

		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhzf2HMk2q6tM-y-ICTesCzKXwSZHq47A&libraries=places" type="text/javascript"></script>
		
		<script src="jquery.geocomplete.js"></script>
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="theme-color" content="#000000">

		<meta name="description" content="Servmanity is a community services marketplace where trusted professionals are empowered to meet the needs of their neighbors.">

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-99971591-1', 'auto');
		  ga('send', 'pageview');

		</script>


	</head>

	<body>

		<% unless @hide_header %>
			
			<%= render 'headers/main_header' %>
			
			<%# render 'modals/main_menu' %>
		<%end%>

		<%= render 'charges/bank_account_form_modal' %>
		<%= render 'modals/service_request_when' %>

		<div class="content-container">

			<%= yield %>

		</div>
		
		<% if @fixed_bottom_cta %>
			<%# render 'modals/fixed_bottom_cta' %>
		<%end%>

		<% unless @hide_header or @hide_footer %>
			<%= render 'layouts/footer' %>
		<%end%>
		
	</body>

</html>